version: '3.9'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: luka23012005
      MYSQL_DATABASE: bp_2_projekt
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5